name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master  # Adjust to your default branch

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Specify the .NET SDK version you need

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run Tests with Code Coverage
      run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4 # Uses the Codecov GitHub Action
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
